#!/bin/bash

mydir="$(dirname $(readlink -f "$0"))"
export PATH=$PATH:$mydir/lib

config_file=${config_file-$1}

if [ ! "$config_file" ]; then
    config_file=$mydir/backupqueue.conf
fi

. $config_file

new_queue="${backup_queue}.new"

export backup_name backup_contact location_info metadata_file backup_queue
next_sn=$(get-next-harddrive)

set -e
tail -n +2 ${backup_queue} >$new_queue
head -n 1 ${backup_queue} >>$new_queue

mv $new_queue $backup_queue
